const { sqliteTable, text, integer, real } = require('drizzle-orm/sqlite-core');
const { sql } = require('drizzle-orm');

const users = sqliteTable('users', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  password_hash: text('password_hash').notNull(),
  role: text('role', { enum: ['owner', 'staff'] }).notNull().default('staff'),
  is_active: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  created_at: text('created_at').notNull().default(sql`(datetime('now'))`),
  updated_at: text('updated_at').notNull().default(sql`(datetime('now'))`),
});

const shopProfile = sqliteTable('shop_profile', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  shop_name: text('shop_name').notNull(),
  owner_name: text('owner_name').notNull(),
  address: text('address'),
  city: text('city'),
  state: text('state'),
  pincode: text('pincode'),
  phone: text('phone'),
  gstin: text('gstin'),
  fssai_number: text('fssai_number'),
  logo_path: text('logo_path'),
  upi_id: text('upi_id'),
  low_stock_threshold: real('low_stock_threshold').notNull().default(5),
  expiry_reminder_days: integer('expiry_reminder_days').notNull().default(30),
  whatsapp_enabled: integer('whatsapp_enabled', { mode: 'boolean' }).notNull().default(true),
  invoice_prefix: text('invoice_prefix').notNull().default('AGR'),
  invoice_counter: integer('invoice_counter').notNull().default(0),
  terms_conditions: text('terms_conditions'),
  created_at: text('created_at').notNull().default(sql`(datetime('now'))`),
  updated_at: text('updated_at').notNull().default(sql`(datetime('now'))`),
});

const categories = sqliteTable('categories', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  name_hindi: text('name_hindi'),
  description: text('description'),
  icon: text('icon'),
  parent_id: integer('parent_id'),
  is_active: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  sort_order: integer('sort_order').notNull().default(0),
  created_at: text('created_at').notNull().default(sql`(datetime('now'))`),
});

const products = sqliteTable('products', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  name_hindi: text('name_hindi'),
  sku: text('sku').unique(),
  barcode: text('barcode'),
  category_id: integer('category_id').references(() => categories.id),
  description: text('description'),
  brand: text('brand'),
  unit: text('unit').notNull().default('piece'),
  purchase_price: integer('purchase_price').notNull().default(0),
  selling_price: integer('selling_price').notNull().default(0),
  mrp: integer('mrp').notNull().default(0),
  gst_rate: integer('gst_rate').notNull().default(0),
  hsn_code: text('hsn_code'),
  current_stock: real('current_stock').notNull().default(0),
  min_stock_alert: real('min_stock_alert').notNull().default(5),
  expiry_date: text('expiry_date'),
  batch_number: text('batch_number'),
  image_path: text('image_path'),
  is_active: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  created_at: text('created_at').notNull().default(sql`(datetime('now'))`),
  updated_at: text('updated_at').notNull().default(sql`(datetime('now'))`),
});

const stockTransactions = sqliteTable('stock_transactions', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  product_id: integer('product_id').notNull().references(() => products.id),
  transaction_type: text('transaction_type', { enum: ['IN', 'OUT', 'ADJUSTMENT', 'RETURN'] }).notNull(),
  quantity: real('quantity').notNull(),
  previous_stock: real('previous_stock').notNull(),
  new_stock: real('new_stock').notNull(),
  reference_id: integer('reference_id'),
  notes: text('notes'),
  created_by: integer('created_by').references(() => users.id),
  created_at: text('created_at').notNull().default(sql`(datetime('now'))`),
});

const customers = sqliteTable('customers', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  name: text('name').notNull(),
  phone: text('phone').notNull().unique(),
  whatsapp_number: text('whatsapp_number'),
  email: text('email'),
  address: text('address'),
  village: text('village'),
  taluka: text('taluka'),
  district: text('district'),
  pincode: text('pincode'),
  gstin: text('gstin'),
  total_purchases: integer('total_purchases').notNull().default(0),
  total_due: integer('total_due').notNull().default(0),
  notes: text('notes'),
  is_active: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  created_at: text('created_at').notNull().default(sql`(datetime('now'))`),
  updated_at: text('updated_at').notNull().default(sql`(datetime('now'))`),
});

const bills = sqliteTable('bills', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  bill_number: text('bill_number').notNull().unique(),
  customer_id: integer('customer_id').references(() => customers.id),
  customer_name: text('customer_name').notNull(),
  customer_phone: text('customer_phone'),
  customer_address: text('customer_address'),
  customer_gstin: text('customer_gstin'),
  bill_date: text('bill_date').notNull(),
  due_date: text('due_date'),
  subtotal: integer('subtotal').notNull().default(0),
  discount_amount: integer('discount_amount').notNull().default(0),
  discount_percent: real('discount_percent').notNull().default(0),
  taxable_amount: integer('taxable_amount').notNull().default(0),
  cgst_amount: integer('cgst_amount').notNull().default(0),
  sgst_amount: integer('sgst_amount').notNull().default(0),
  igst_amount: integer('igst_amount').notNull().default(0),
  total_amount: integer('total_amount').notNull().default(0),
  paid_amount: integer('paid_amount').notNull().default(0),
  due_amount: integer('due_amount').notNull().default(0),
  payment_status: text('payment_status', { enum: ['PAID', 'PARTIAL', 'UNPAID'] }).notNull().default('UNPAID'),
  payment_method: text('payment_method').notNull().default('CASH'),
  notes: text('notes'),
  created_by: integer('created_by').references(() => users.id),
  created_at: text('created_at').notNull().default(sql`(datetime('now'))`),
  updated_at: text('updated_at').notNull().default(sql`(datetime('now'))`),
});

const productVariants = sqliteTable('product_variants', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  product_id: integer('product_id').notNull().references(() => products.id),
  label: text('label').notNull(),
  pack_size: real('pack_size').notNull(),
  unit: text('unit').notNull(),
  sku: text('sku').unique(),
  purchase_price: integer('purchase_price').notNull().default(0),
  selling_price: integer('selling_price').notNull().default(0),
  mrp: integer('mrp').notNull().default(0),
  current_stock: real('current_stock').notNull().default(0),
  min_stock_alert: real('min_stock_alert').notNull().default(5),
  is_active: integer('is_active', { mode: 'boolean' }).notNull().default(true),
  created_at: text('created_at').notNull().default(sql`(datetime('now'))`),
  updated_at: text('updated_at').notNull().default(sql`(datetime('now'))`),
});

const billItems = sqliteTable('bill_items', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  bill_id: integer('bill_id').notNull().references(() => bills.id),
  product_id: integer('product_id').references(() => products.id),
  variant_id: integer('variant_id').references(() => productVariants.id),
  product_name: text('product_name').notNull(),
  hsn_code: text('hsn_code'),
  unit: text('unit').notNull(),
  quantity: real('quantity').notNull(),
  rate: integer('rate').notNull(),
  mrp: integer('mrp'),
  discount_percent: real('discount_percent').notNull().default(0),
  taxable_amount: integer('taxable_amount').notNull().default(0),
  gst_rate: integer('gst_rate').notNull().default(0),
  cgst: integer('cgst').notNull().default(0),
  sgst: integer('sgst').notNull().default(0),
  igst: integer('igst').notNull().default(0),
  total_amount: integer('total_amount').notNull().default(0),
});

const payments = sqliteTable('payments', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  bill_id: integer('bill_id').notNull().references(() => bills.id),
  customer_id: integer('customer_id').references(() => customers.id),
  amount: integer('amount').notNull(),
  payment_method: text('payment_method').notNull(),
  reference_number: text('reference_number'),
  notes: text('notes'),
  created_at: text('created_at').notNull().default(sql`(datetime('now'))`),
});

const notifications = sqliteTable('notifications', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  type: text('type', { enum: ['LOW_STOCK', 'EXPIRY', 'DUE_PAYMENT'] }).notNull(),
  title: text('title').notNull(),
  message: text('message').notNull(),
  reference_id: integer('reference_id'),
  reference_type: text('reference_type'),
  is_read: integer('is_read', { mode: 'boolean' }).notNull().default(false),
  created_at: text('created_at').notNull().default(sql`(datetime('now'))`),
});

const whatsappMessages = sqliteTable('whatsapp_messages', {
  id: integer('id').primaryKey({ autoIncrement: true }),
  customer_id: integer('customer_id').references(() => customers.id),
  phone: text('phone').notNull(),
  message_type: text('message_type', { enum: ['BILL', 'REMINDER', 'CUSTOM'] }).notNull(),
  message: text('message').notNull(),
  status: text('status', { enum: ['SENT', 'FAILED', 'PENDING'] }).notNull().default('PENDING'),
  reference_id: integer('reference_id'),
  created_at: text('created_at').notNull().default(sql`(datetime('now'))`),
});

module.exports = {
  users,
  shopProfile,
  categories,
  products,
  productVariants,
  stockTransactions,
  customers,
  bills,
  billItems,
  payments,
  notifications,
  whatsappMessages,
};
